### ISSUE TITLE
Steps to disable/remove theme from GRUB

### ISSUE THREAD

**Issue by sametaor** [Lxtharia/double-minegrub-menu#2]
Hi! I am an arch linux newbie who recently got towards making a dual booting setup with Win10 just 3 days ago, and I just wanted to know what steps one should take in order to disable or remove this theme from the GRUB bootloader, apart from that disabling part you mentioned in the README. This is for scenarios where I might want to change over to some other theme (tho it'd take a long time for me to move over to another one, this one is too perfect haha) later on, just in case I might run into some issues later on.

Thanks!

**Comment by Lxtharia** [comment]
Thanks :D 

The disabling part only disables the first (fake) menu and is specifically for this double theming. To remove it, also delete the two files that you copied.

To change grub themes, you can just change or comment out the GRUB_THEME line in your /etc/defaults/grub file and regenerate /boot/grub/grub.cfg with grub-mkconfig. :)

In the unlikely case that you really want to get rid of everything, disable and remove the service that changes background and splash text and delete the files from the boot partition. Now you are minegrub free until you realize there is no better theme to be found x)

**Comment by sametaor** [comment]
> Thanks :D
> 
> The disabling part only disables the first (fake) menu and is specifically for this double theming. To remove it, also delete the two files that you copied.
> 
> To change grub themes, you can just change or comment out the GRUB_THEME line in your /etc/defaults/grub file and regenerate /boot/grub/grub.cfg with grub-mkconfig. :)
> 
> In the unlikely case that you really want to get rid of everything, disable and remove the service that changes background and splash text and delete the files from the boot partition. Now you are minegrub free until you realize there is no better theme to be found x)

Thanks a lot for the clarification!
